### ISSUE TITLE
Uses deprecated 'set-output' command

### ISSUE THREAD

**Issue by idahogurl** [thomaseizinger/create-pull-request#221]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I will see if I have time to create a PR if you want me to.

**Comment by thomaseizinger** [comment]
> I will see if I have time to create a PR if you want me to.

That would be much appreciated, I don't actively maintain this action.

**Comment by ZebraFlesh** [comment]
@thomaseizinger We're coming up on the deprecation deadline. Is it possible for you to perform a release with this fix?

**Comment by thomaseizinger** [comment]
> @thomaseizinger We're coming up on the deprecation deadline. Is it possible for you to perform a release with this fix?

Sorry, will aim to get around to it next week.
