### ISSUE TITLE
Add support for creating PR's in GHES (GitHub enterprise server) behind proxy

### ISSUE THREAD

**Issue by sethumadhav07** [thomaseizinger/create-pull-request#39]
Currently 'create-pull-request' can't create PR's in GHES and behind proxy. Is it possible to add support? That would be a very nice addition. 

octokit constructor has options to include base url as well as proxy : https://github.com/octokit/octokit.js#constructor-options

e.g. 

  ```
const proxy = new HttpsProxyAgent(process.env.http_proxy);
     let octokit = new Octokit({
        baseUrl: `${baseurl}/api/v3`,
        request: {
          agent: proxy,
        },
      });
```

Is it also possible to improve on additional outputs (e.g. html_url) instead of constructing url ourselves?

```
const html_url = pullRequest.data.html_url;
 setOutput("html_url", html_url);
```

**Comment by thomaseizinger** [comment]
> Currently 'create-pull-request' can't create PR's in GHES and behind proxy. Is it possible to add support? That would be a very nice addition.

Yep, I would accept a PR for that.

> Is it also possible to improve on additional outputs (e.g. html_url) instead of constructing url ourselves?

Yep, also happy to accept a PR for that.
