### ISSUE TITLE
How to retrieve the error message from the github action

### ISSUE THREAD

**Issue by geoffreyIOOF** [thomaseizinger/create-pull-request#56]
Is there a way to access the error message from the github action (next step checking from failure) set by the setFailed (Index.ts L38) ?

**Comment by thomaseizinger** [comment]
Do you mean "access" as in programmatically accessing it?

As far as I know, it is only shown in the log that is presented to the user. How would you like to access it?

**Comment by geoffreyIOOF** [comment]
My question is more related with the core library I guess , I can't find a way to retrieve the error message from the workflow, as it s only shown in the log. Maybe you know a way to access the log from the workflow.

If there is no way to access the error message from the workflow a work-around would be to set an output value in the cacth block

```
  setOutput('html_url', htmlUrl);
  } catch (error) {
   setOutput('error', error.message);
  }
```
I was thinking of accessing it like this ${{ steps.cpr.outputs.error}} :
- name: Create pull request
  id: cpr
  uses: thomaseizinger/create-pull-request@master
  with:
    GITHUB_TOKEN: ${{ secrets.AUTOMATION }}
    head: ${{ github.event.inputs.branch }}
    base: release-candidate
    title: "${{ github.event.inputs.branch }} to release-candidate"
- name: Check failed PR (skip merging stage)
  if: ${{ failure() }}
  run: echo "${{ steps.cpr.outputs.error}}"

Regards

**Comment by thomaseizinger** [comment]
I don't quite understand what you are trying to achieve. Any error that happens is printed in the log. For example here: https://github.com/vitalyal/create-pull-request/runs/3168270789?check_suite_focus=true#step:4:7

**Comment by geoffreyIOOF** [comment]
I want my next step to check the error (but I can't find a way to access it)
- name: Check Pull request
   if: failure() && error.contains("Reviews may only be requested from collaborators")
   run: do something
 - name: Check Pull request
   if: failure() && error.contains("Conflicts")
   run: do something

**Comment by thomaseizinger** [comment]
If you want to complex processing like this, maybe have a look at the `gh` CLI? This action predates the CLI. Or at least my knowledge about it :D

**Comment by geoffreyIOOF** [comment]
No worries, Thanks for your help anyway.
